version: '2.1'

networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"
    depends_on:
      - db

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"
    depends_on:
      - db

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - servers
    ports:
      - "5432:5432"
